# The contents of this file are executed as DFHack commands
# when a world is loaded - good for bugfixes and other options

# disable persistent commands
# (so that state will always match dfhack tab, re-enabling if on)
multicmd autolabor 0; workflow disable; autonestbox stop; seedwatch stop;

# Run the commands written by the dfhack tab(s)
script PyLNP_dfhack_onLoad.init

#Add your own commands below here!...
